services:

  backend:
    image: mohamedabdellhay/winsome-task-backend:latest
    container_name: winsome_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@172.17.0.1:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: 3001
    ports:
      - "3001:3001"

  frontend:
    image: mohamedabdellhay/winsome-task-frontend:latest
    container_name: winsome_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
      API_URL: http://backend:3001
    ports:
      - "8080:8080"
    depends_on:
      - backend


