services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: winsome_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/hotel_booking
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node dist/main"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: winsome_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: hotel_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
